name: Build Index

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build index
        run: node scripts/build-index.js
      - name: Commit index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: dist/index.json
          commit_message: "Update index.json"
